In [1]:
import sys
import os
sys.path.insert(0,os.path.abspath('..'))
from spatial_graphs.AmiraSpatialGraph import AmiraSpatialGraph,SpatialGraphData
import pathlib
import glob
import numpy as np

In [2]:
def get_tx_mat_from_hx_file(file, lines):
    str_to_compare = '"'+os.path.basename(file)+'"'+ ' setTransform '
    tx_mat = []
    tx_mat_np = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]).reshape(4,4)
    for line in lines:
        if line.startswith(str_to_compare):
            #tx_mat = (line[len(str_to_compare):-1].split(' '))
            for num in (line[len(str_to_compare):-1].split(' ')):
                tx_mat.append(float(num))
            tx_mat_np = np.array(tx_mat).reshape(4,4)
            break
        
    return tx_mat_np

In [91]:
# basepath = '/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/'
# animal_name = 'RA_20160307_4x_for_merge'

# cell_name = ''

# full_path = basepath + animal_name + '/' + cell_name  + 'ascii/'

# file_pattern = 'S{:02d}*.am'

# tx_file = basepath + animal_name + '/' + cell_name + 'Untitled2.hx'

# op_path = '/nas1/Data_Mythreya/MotorCortexProject/Auto_Merged_Spatial_Graphs/'

# pathlib.Path(op_path).mkdir(exist_ok=True)

#path = path + 'ascii/'




In [ ]:
#
tx_file = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/contours/aligntobarrel.hx'.format(animal_name)

rabies_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/rabies/'.format(animal_name)
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V0/0_Inputs/Landmarks/Manual/Rabies/NeuN/{}/'.format(animal_name)


In [96]:
sg_3d = AmiraSpatialGraph(glob.glob(full_path + file_pattern.format(1))[0],read_header_only=True)
#landmarks3d = Landmarks()
#landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 100

with open(tx_file,'r') as f:
    lines = f.readlines()
        
for s in range(100):
    if len(glob.glob(full_path + file_pattern.format(s)))>0:
        file = glob.glob(full_path + file_pattern.format(s))[0]
        print(file)
        sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])
        

        # read tx mat from the file
        tx_mat_np = get_tx_mat_from_hx_file(file,lines)
        print(tx_mat_np)
        print(len(sg.barrels.all_rows_graphdata.edge_pt_coords))
        #sg.set_z_coord(z_coord)
        sg.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
        #sg.graph_data = sg.combine_subgraphs([sg.pia,sg.wm,\
        #                                               sg.bvs,sg.barrels.all_rows_graphdata,\
        #                                               sg.neuron.all_neurites_subgraphdata])
        z_coord+=z_cood_offset

        sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
        
        #if z_coord == 4000:
        #    break
        
# merge the neuron morph
sg = AmiraSpatialGraph(glob.glob(full_path+'RA*.am')[0],axis_directions=[1,1,1])
#tx_mat_np = get_tx_mat_from_hx_file(cell_name,lines)
#print(tx_mat_np)
#sg.set_z_coord(0)
#sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

# write it
sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')
    

/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/RA_20160307_4x_for_merge/ascii/S01.am
[[ 9.71817e-01  2.35734e-01  0.00000e+00  0.00000e+00]
 [-2.35734e-01  9.71817e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 9.42027e+02 -7.10669e+02 -3.81470e-06  1.00000e+00]]
0
/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/RA_20160307_4x_for_merge/ascii/S02.am
[[ 9.80600e-01  1.96020e-01  0.00000e+00  0.00000e+00]
 [-1.96020e-01  9.80600e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  9.99999e-01  0.00000e+00]
 [ 7.81992e+02 -2.24623e+03  1.00000e+02  1.00000e+00]]
0
/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/RA_20160307_4x_for_merge/ascii/S03.am
[[ 9.52513e-01  3.04498e-01  0.00000e+00  0.00000e+00]
 [-3.04498e-01  9.52513e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.76556e+03

[[ 9.91716e-01 -1.28452e-01  0.00000e+00  0.00000e+00]
 [ 1.28452e-01  9.91716e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.45370e+03 -3.47043e+03  2.80000e+03  1.00000e+00]]
0
/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/RA_20160307_4x_for_merge/ascii/S30.am
[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.93266e+03 -5.28821e+03  2.90000e+03  1.00000e+00]]
0
/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/RA_20160307_4x_for_merge/ascii/S31.am
[[ 9.90656e-01  1.36387e-01  0.00000e+00  0.00000e+00]
 [-1.36387e-01  9.90656e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.04810e+03 -6.26235e+03  3.00000e+03  1.00000e+00]]
0
/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_201

In [60]:
sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'_temp.am')

In [422]:
#sg.graph_data.edge_labels
#%run AmiraSpatialGraph.ipynb
sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')

In [423]:
op_path+animal_name+'_'+cell_name+'.am'

'/nas1/Data_Mythreya/MotorCortexProject/Auto_Merged_Spatial_Graphs/RA_20171214_1_Cell_A.am'

In [151]:
sg_3d = AmiraSpatialGraph(glob.glob(path + file_pattern.format(1))[0],read_header_only=True)
#landmarks3d = Landmarks()
#landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 100
for s in range(100):
    if len(glob.glob(path + file_pattern.format(s)))>0:
        file = glob.glob(path + file_pattern.format(s))[0]
        sg = AmiraSpatialGraph(file,axis_directions=[1,1,1],read_transformation_matrix=True)
        
        print(file)
        print(sg.transformation_matrix)

        sg.apply_transformation()
        
        z_coord+=z_cood_offset

        #sg.set_z_coord(z_coord)
        
        sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

        
        #if z_coord == 4000:
        #    break
        


sg_3d.write_spatial_graph(op_path+'{}.am'.format(animal_name))
    

/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S01.am
[]
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 100.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S02.am
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 100.0, 1.0]
[0.983868, 0.178893, 0.0, 0.0, -0.178893, 0.983868, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 942.097, -1574.59, 200.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S03.am
[0.983868, 0.178893, 0.0, 0.0, -0.178893, 0.983868, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 942.097, -1574.59, 200.0, 1.0]
[0.990497, 0.137535, 0.0, 0.0, -0.137535, 0.990497, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 807.53, -1754.88, 300.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S04.am
[0.990497, 0.137535, 0.0, 0.0, -0.137

[0.999645, 0.0266571, 0.0, 0.0, -0.0266571, 0.999645, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -2128.5, -5033.76, 2500.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S26.am
[0.999645, 0.0266571, 0.0, 0.0, -0.0266571, 0.999645, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -2128.5, -5033.76, 2500.0, 1.0]
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -3169.85, -5549.42, 2600.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S27.am
[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -3169.85, -5549.42, 2600.0, 1.0]
[0.999779, 0.0210083, 0.0, 0.0, -0.0210083, 0.999779, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -2042.79, -5675.1, 2700.0, 1.0]
/nas1/Data_Mythreya/MotorCortexProject/V4/auto_merge_test/Cell_B_contour_cell_merging/section_graphs/ascii/S28.am
[0.999779, 0.0210083, 0.0, 0.0, -0.0210083, 0.999779, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -2042.79, -5675.1, 2700.0, 1.0]
[0.999

In [4]:
#op_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/'
axis_direction = [1,-1,-1]
sg_3d_mirrored = AmiraSpatialGraph(op_path+'{}.am'.format(animal_name),axis_directions=axis_direction)
sg_3d_mirrored.write_spatial_graph(op_path+'{}.am'.format(animal_name))

landmarks3d.set_axis_directions(axis=axis_direction)
landmarks3d.write_landmarks(op_path+'{}_rabies_landmarks.LandmarkAscii'.format(animal_name))
landmarks3d_neun.set_axis_directions(axis=axis_direction)
landmarks3d_neun.write_landmarks(op_path+'{}_neun_landmarks.LandmarkAscii'.format(animal_name))

A1 Barrel height 50.0
B1 Barrel height 100.0
B2 Barrel height 50.0
B3 Barrel height 100.0
B4 Barrel height 50.0
C1 Barrel height 50.0
C2 Barrel height 150.0
C3 Barrel height 100.0
C4 Barrel height 100.0
C5 Barrel height 50.0
C6 Barrel height 0.0
D1 Barrel height 0.0
D2 Barrel height 0.0
D3 Barrel height 0.0
D4 Barrel height 50.0
D5 Barrel height 50.0
E1 Barrel height 0.0
E2 Barrel height 0.0
E3 Barrel height 0.0
E4 Barrel height 0.0
Alpha Barrel height 0.0
Beta Barrel height 50.0
Gamma Barrel height 50.0
Delta Barrel height 0.0
