In [9]:
import sys
import os
sys.path.insert(0,os.path.abspath('..'))
from spatial_graphs.AmiraSpatialGraph import AmiraSpatialGraph,SpatialGraphData
from spatial_graphs.Landmarks import Landmarks
from spatial_graphs.Surfaces import Surface
import pathlib
import glob
import numpy as np

In [10]:
def get_tx_mat_from_hx_file(file, lines):
    str_to_compare = '"'+os.path.basename(file)+'"'+ ' setTransform '
    tx_mat = []
    tx_mat_np = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]).reshape(4,4)
    for line in lines:
        if line.startswith(str_to_compare):
            #tx_mat = (line[len(str_to_compare):-1].split(' '))
            for num in (line[len(str_to_compare):-1].split(' ')):
                tx_mat.append(float(num))
            tx_mat_np = np.array(tx_mat).reshape(4,4)
            break
        
    return tx_mat_np

In [11]:
def get_tx_mat_from_hx_file_using_filename(file_pattern, lines):
    str_to_compare = '"'+file_pattern+'"'+ ' setTransform '
    print(str_to_compare)
    tx_mat = []
    tx_mat_np = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]).reshape(4,4)
    for line in lines:
        if line.startswith(str_to_compare):
            #tx_mat = (line[len(str_to_compare):-1].split(' '))
            for num in (line[len(str_to_compare):-1].split(' ')):
                tx_mat.append(float(num))
            tx_mat_np = np.array(tx_mat).reshape(4,4)
            break
        
    return tx_mat_np

In [12]:
# basepath = '/nas1/MotorCortex/Data/2_Morphologies_ASCs_and_Hocs/Finalround_newly_added/RA_20160307/'
# animal_name = 'RA_20160307_4x_for_merge'

# cell_name = ''

# full_path = basepath + animal_name + '/' + cell_name  + 'ascii/'

# file_pattern = 'S{:02d}*.am'

# tx_file = basepath + animal_name + '/' + cell_name + 'Untitled2.hx'

# op_path = '/nas1/Data_Mythreya/MotorCortexProject/Auto_Merged_Spatial_Graphs/'

# pathlib.Path(op_path).mkdir(exist_ok=True)

#path = path + 'ascii/'




# Merge NeuN 

In [23]:
animal_name = 'MG50_lhs'
#s1_or_m1 = 'vM1/Central_Axis'
#s1_or_m1 = 'vS1'

tx_file = '/nas1/Data_Mythreya/MotorCortexProject/V11/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/aligntobarrel.hx'.format(animal_name)
#tx_file = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/align.hx'

section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/V11/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/'.format(animal_name)
#section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

file_pattern = 'S{:03d}*.am'
#file_pattern = 'S{:02d}_00.tif'

barrel_name = 'D3'
offset = 10# microns
#rabies_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/rabies/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_Central_Axis_Radius_250um/{}/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_aman/For_/For_Mythreya/NeuN_project/{}/{}/'.format(animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts/{}/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/'
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

In [24]:
#sg_3d = AmiraSpatialGraph(glob.glob(section_graphs_path + file_pattern.format(2))[0],read_header_only=True)
#landmarks3d = Landmarks()
landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 50

with open(tx_file,'r') as f:
    lines = f.readlines()
        
for s in range(120):
    if len(glob.glob(section_graphs_path + file_pattern.format(s)))>0:
    #if 1:
        file = glob.glob(section_graphs_path + file_pattern.format(s))[0]
        #print(file)
        #sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])

        # read tx mat from the file
        tx_mat_np = get_tx_mat_from_hx_file(file,lines)
        #print('S{:02d}_00.tif'.format(s))
        #tx_mat_np = get_tx_mat_from_hx_file_using_filename('S{:02d}_00.tif'.format(s),lines)
        print(tx_mat_np)
        #print(len(sg.barrels.all_rows_graphdata.edge_pt_coords))
        #sg.set_z_coord(0)
        #sg.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
        #sg.set_z_coord(z_coord)
        #sg.graph_data = sg.combine_subgraphs([sg.pia,sg.wm,\
        #                                              sg.bvs,sg.barrels.all_rows_graphdata,\
        #                                              sg.neuron.all_neurites_subgraphdata])
        z_coord+=z_cood_offset

        #sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
        #print(glob.glob(neun_landmarks_path+'S{}'.format(s)+'/landmarks.landmarkAscii'))
        #if len(glob.glob(neun_landmarks_path+'/S_{}/landmarks{}'.format(s)+'.landmarkAscii'))>0:
        if len(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii'))>0:
            #print(glob.glob(neun_landmarks_path+'Landmarks{}'.format(s)+'*Ascii')[0])
            landmark_filename = glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0]
            # remove boundary spurious neun counts
            l = Landmarks( landmark_filename )
            bounds = Surface(pts=l.pts).surface.GetBounds()
            print(bounds)
            cropped_pts = l.get_landmarks_in_bounding_box([bounds[0],bounds[1],bounds[2],bounds[3],bounds[4]+offset,bounds[5]-offset])
            #andmark_filename =  glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0]
            #print(landmark_filename)
            l = Landmarks(pts=cropped_pts)
            #l.set_z_coord(0)
            l.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
            l.add_z_offset(z_coord)
            #l.set_z_coord(z_coord)
            
            #l.write_landmarks(neun_landmarks_path+str(s)+'_'+os.path.basename(landmark_filename))
            #print(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            
            #print(len(l.pts))
            landmarks3d_neun.append_landmarks(l.pts)
        
#         if z_coord == 1000:
#             break
# if animal_name == 'MG48_rhs' or animal_name == 'MG49_rhs' or animal_name == 'MG50_rhs':
#     axis_direction= [-1,1,1]
#     landmarks3d_neun.set_axis_directions(axis=axis_direction)
landmarks3d_neun.write_landmarks(neun_landmarks_path+animal_name+\
                                 '_neun_landmarks_central_axis_3d_z_boundary_trimmed_{}um.LandmarkAscii'.format(offset))
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))

# merge the neuron morph
# sg = AmiraSpatialGraph(glob.glob(full_path+'RA*.am')[0],axis_directions=[1,1,1])
# #tx_mat_np = get_tx_mat_from_hx_file(cell_name,lines)
# #print(tx_mat_np)
# #sg.set_z_coord(0)
# #sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
# sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

# write it
#sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))  

[[ 9.39696e-01  3.42011e-01  0.00000e+00  0.00000e+00]
 [-3.42011e-01  9.39696e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 3.29424e+03  4.04400e+03 -1.23978e-05  1.00000e+00]]
[[ 9.48357e-01  3.17206e-01  0.00000e+00  0.00000e+00]
 [-3.17206e-01  9.48357e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.94487e+03  3.28322e+03 -1.52588e-05  1.00000e+00]]
[[ 9.61720e-01  2.74033e-01  0.00000e+00  0.00000e+00]
 [-2.74033e-01  9.61720e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 3.10751e+03  2.84669e+03 -1.71661e-05  1.00000e+00]]
[[ 9.75896e-01  2.18236e-01  0.00000e+00  0.00000e+00]
 [-2.18236e-01  9.75896e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.20357e+03  3.04979e+03  1.90735e-06  1.00000e+00]]
[[ 9.78280e-01  2.07290e-01  0.00000e+00  0.00000e+00]
 [-2.07290e-01  9.78280e-01  0.00000e+00  0.00000e+00]
 [ 0.0

(4698.8994140625, 5870.12060546875, 2222.39599609375, 3452.180908203125, 6.5553202629089355, 57.24580001831055)
[[ 9.90587e-01  1.36882e-01  0.00000e+00  0.00000e+00]
 [-1.36882e-01  9.90587e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 9.22656e+01 -2.40448e+03 -7.62939e-06  1.00000e+00]]
(6016.01123046875, 7165.0546875, 2410.7919921875, 3616.148193359375, 4.569579601287842, 57.13330078125)
[[ 9.29311e-01  3.69297e-01  0.00000e+00  0.00000e+00]
 [-3.69297e-01  9.29311e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.69948e+03 -3.03688e+03  7.62939e-06  1.00000e+00]]
(5196.60791015625, 6298.19384765625, 2009.8179931640625, 3116.00146484375, 3.897589921951294, 54.630699157714844)
[[ 9.92698e-01  1.20628e-01  0.00000e+00  0.00000e+00]
 [-1.20628e-01  9.92698e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.30884e+01 -2.25836e+03 -7.62939e-06  1.00000e+00]]
(5968.7

 [ 9.21189e+02 -3.53308e+03 -1.52588e-05  1.00000e+00]]
[[ 9.93721e-01  1.11886e-01  0.00000e+00  0.00000e+00]
 [-1.11886e-01  9.93721e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-5.39881e+02 -2.93540e+03 -7.62939e-06  1.00000e+00]]
[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.79735e+03 -2.36016e+03  0.00000e+00  1.00000e+00]]
[[ 9.93895e-01  1.10326e-01  0.00000e+00  0.00000e+00]
 [-1.10326e-01  9.93895e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-6.49537e+02 -2.81999e+03  7.62939e-06  1.00000e+00]]
[[ 9.77526e-01  2.10813e-01  0.00000e+00  0.00000e+00]
 [-2.10813e-01  9.77526e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-7.08081e+01 -3.89406e+03  0.00000e+00  1.00000e+00]]
[[ 9.90801e-01  1.35329e-01  0.00000e+00  0.00000e+00]
 [-1.

# Inverse Merge NeuN 

In [106]:
animal_name = 'MG50_lhs'
#s1_or_m1 = 'vM1/Central_Axis'
#s1_or_m1 = 'vS1'

tx_file = '/nas1/Data_Mythreya/MotorCortexProject/V11/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/aligntobarrel.hx'.format(animal_name)
#tx_file = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/align.hx'
#'Step_0_landmarks_within_column_MG50_lhs_central_axis_3d.landmarksAscii'
section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/V10/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/'.format(animal_name)
#section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

file_pattern = 'S{:03d}*.am'
#file_pattern = 'S{:02d}_00.tif'

barrel_name = 'D3'
#rabies_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/rabies/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_Central_Axis_Radius_250um/{}/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_aman/For_/For_Mythreya/NeuN_project/{}/{}/'.format(animal_name,barrel_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts/{}/'.format(animal_name)
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/'
#neun_landmarks_transformed_sections_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

In [107]:
#sg_3d = AmiraSpatialGraph(glob.glob(section_graphs_path + file_pattern.format(2))[0],read_header_only=True)
#landmarks3d = Landmarks()
landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 50

with open(tx_file,'r') as f:
    lines = f.readlines()
        
for s in range(120):
    if len(glob.glob(section_graphs_path + file_pattern.format(s)))>0:
    #if 1:
        file = glob.glob(section_graphs_path + file_pattern.format(s))[0]
        #print(file)
        #sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])

        # read tx mat from the file
        tx_mat_np = get_tx_mat_from_hx_file(file,lines)
        #print('S{:02d}_00.tif'.format(s))
        #tx_mat_np = get_tx_mat_from_hx_file_using_filename('S{:02d}_00.tif'.format(s),lines)
        print(tx_mat_np)
        #print(len(sg.barrels.all_rows_graphdata.edge_pt_coords))
        #sg.set_z_coord(0)
        #sg.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
        #sg.set_z_coord(z_coord)
        #sg.graph_data = sg.combine_subgraphs([sg.pia,sg.wm,\
        #                                              sg.bvs,sg.barrels.all_rows_graphdata,\
        #                                              sg.neuron.all_neurites_subgraphdata])
        z_coord+=z_cood_offset

        #sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
        #print(glob.glob(neun_landmarks_path+'S{}'.format(s)+'/landmarks.landmarkAscii'))
        if len(glob.glob(neun_landmarks_path+'/S_{}/landmarks{}'.format(s)+'.landmarkAscii'))>0:
        #if len(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii'))>0:
            #print(glob.glob(neun_landmarks_path+'Landmarks{}'.format(s)+'*Ascii')[0])
            #landmark_filename =  glob.glob(neun_landmarks_path+'/S_{}/landmarks{}'.format(s)+'.landmarkAscii')[0]
            landmark_filename =  glob.glob(neun_landmarks_path+'/S_{}/landmarks{}'.format(s)+'.landmarkAscii')[0]
            #andmark_filename =  glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0]
            print(landmark_filename)
            l = Landmarks( landmark_filename )
            l.set_z_coord(0)
            l.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True,inverse=True)
            #l.add_z_offset(z_coord)
            l.set_z_coord(z_coord)
            l.write_landmarks(neun_landmarks_path+str(s)+'_'+os.path.basename(landmark_filename))
            #print(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            
            
            #print(len(l.pts))
            landmarks3d_neun.append_landmarks(l.pts)
        
#         if z_coord == 1000:
#             break
# if animal_name == 'MG48_rhs' or animal_name == 'MG49_rhs' or animal_name == 'MG50_rhs':
#     axis_direction= [-1,1,1]
#     landmarks3d_neun.set_axis_directions(axis=axis_direction)
#landmarks3d_neun.write_landmarks(neun_landmarks_path+animal_name+'_neun_landmarks_vS1_{}.LandmarkAscii'.format(barrel_name))
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))

# merge the neuron morph
# sg = AmiraSpatialGraph(glob.glob(full_path+'RA*.am')[0],axis_directions=[1,1,1])
# #tx_mat_np = get_tx_mat_from_hx_file(cell_name,lines)
# #print(tx_mat_np)
# #sg.set_z_coord(0)
# #sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
# sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

# write it
#sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))  

FileNotFoundError: [Errno 2] No such file or directory: '/nas1/Data_Mythreya/MotorCortexProject/V10/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/MG48.am/aligntobarrel.hx'

In [105]:
# combine barrel landmarks 
path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/'
#path = '/nas1/Data_aman/For_/For_Mythreya/NeuN_project/'

for exp in ['MG50_lhs']:#['MG49_lhs','MG49_rhs','MG50_rhs']:
    pts = []
    for barrel in ['C2','C3','D2','D3']:
        l = Landmarks(path+exp+'/'+exp+'_'+barrel+'/'+'{}_neun_landmarks_vS1_{}.LandmarkAscii'.format(exp,barrel))
        for pt in l.pts:
            pts.append(pt)
    print(len(pts))
    Landmarks(pts=pts).write_landmarks(path+exp+'_neun_landmarks_vS1.LandmarkAscii')
    

33318


In [ ]:
#op_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/'
axis_direction = [-1,1,1]
sg_3d_mirrored = AmiraSpatialGraph(op_path+'{}.am'.format(animal_name),axis_directions=axis_direction)
sg_3d_mirrored.write_spatial_graph(op_path+'{}.am'.format(animal_name))

# landmarks3d.set_axis_directions(axis=axis_direction)
# landmarks3d.write_landmarks(op_path+'{}_rabies_landmarks.LandmarkAscii'.format(animal_name))
landmarks3d_neun.set_axis_directions(axis=axis_direction)
landmarks3d_neun.write_landmarks(op_path+'{}_neun_landmarks.LandmarkAscii'.format(animal_name))

In [ ]:
sg_3d = AmiraSpatialGraph(glob.glob(path + file_pattern.format(1))[0],read_header_only=True)
#landmarks3d = Landmarks()
#landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 100
for s in range(100):
    if len(glob.glob(path + file_pattern.format(s)))>0:
        file = glob.glob(path + file_pattern.format(s))[0]
        sg = AmiraSpatialGraph(file,axis_directions=[1,1,1],read_transformation_matrix=True)
        
        print(file)
        print(sg.transformation_matrix)

        sg.apply_transformation()
        
        z_coord+=z_cood_offset

        #sg.set_z_coord(z_coord)
        
        sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

        
        #if z_coord == 4000:
        #    break
        


sg_3d.write_spatial_graph(op_path+'{}.am'.format(animal_name))
    

# Transforming 3D to section Images

In [ ]:
animal_name = 'MG50_lhs'
#tx_file = '/nas1/Data_Mythreya/MotorCortexProject/V9/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/aligntobarrel.hx'.format(animal_name)
tx_file = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/align.hx'

#section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/V9/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/'.format(animal_name)
section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

#file_pattern = 'S{:03d}*.am'
file_pattern = 'S{:02d}_00.tif'

barrel_name = 'D2'
#rabies_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/rabies/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/'
neun_landmarks_transformed_sections_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

In [ ]:
#sg_3d = AmiraSpatialGraph(glob.glob(section_graphs_path + file_pattern.format(2))[0],read_header_only=True)
#landmarks3d = Landmarks()
landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 50

with open(tx_file,'r') as f:
    lines = f.readlines()
        
for s in range(120):
    #if len(glob.glob(section_graphs_path + file_pattern.format(s)))>0:
    if 1:
        #file = glob.glob(section_graphs_path + file_pattern.format(s))[0]
        #print(file)
        #sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])

        # read tx mat from the file
        #tx_mat_np = get_tx_mat_from_hx_file(file,lines)
        #print('S{:02d}_00.tif'.format(s))
        tx_mat_np = get_tx_mat_from_hx_file_using_filename('S{:02d}_00.tif'.format(s),lines)
        print(tx_mat_np)
        #print(len(sg.barrels.all_rows_graphdata.edge_pt_coords))
        #sg.set_z_coord(0)
        #sg.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
        #sg.set_z_coord(z_coord)
        #sg.graph_data = sg.combine_subgraphs([sg.pia,sg.wm,\
        #                                              sg.bvs,sg.barrels.all_rows_graphdata,\
        #                                              sg.neuron.all_neurites_subgraphdata])
        z_coord+=z_cood_offset

        #sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
        #print(glob.glob(neun_landmarks_path+'S{}'.format(s)+'/landmarks.landmarkAscii'))
        if len(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii'))>0:
            print(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0])
            landmark_filename =  glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0]
            l = Landmarks( landmark_filename )
            #l.set_z_coord(0)
            l.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
            l.write_landmarks(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            #print(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            #l.set_z_coord(z_coord)
            #print(len(l.pts))
            landmarks3d_neun.append_landmarks(l.pts)
        
#         if z_coord == 1000:
#             break
if animal_name == 'MG48_rhs' or animal_name == 'MG49_rhs' or animal_name == 'MG50_rhs':
    axis_direction= [-1,1,1]
    landmarks3d_neun.set_axis_directions(axis=axis_direction)
#landmarks3d_neun.write_landmarks(neun_landmarks_path+'neun_landmarks.LandmarkAscii')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))

# merge the neuron morph
# sg = AmiraSpatialGraph(glob.glob(full_path+'RA*.am')[0],axis_directions=[1,1,1])
# #tx_mat_np = get_tx_mat_from_hx_file(cell_name,lines)
# #print(tx_mat_np)
# #sg.set_z_coord(0)
# #sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
# sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

# write it
#sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))  

# Inverse Transforming 3D to section Images

In [ ]:
animal_name = 'MG50_lhs'
#tx_file = '/nas1/Data_Mythreya/MotorCortexProject/V9/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/aligntobarrel.hx'.format(animal_name)
tx_file = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/align.hx'

#section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/V9/vM1_Ref_Frame/Original_Data/Spatial_Graphs/misc/Section_Graphs/{}.am/'.format(animal_name)
section_graphs_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

#file_pattern = 'S{:03d}*.am'
file_pattern = 'S{:02d}_00.tif'

barrel_name = 'D2'
#rabies_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Section_Graphs/Rabies/{}/rabies/'.format(animal_name)
#neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/Images_For_NeuN_Count_For_Barrels/{}/{}_{}/'.format(animal_name,animal_name,barrel_name)
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/'
neun_landmarks_transformed_sections_path = '/nas1/Data_Mythreya/MotorCortexProject/NeuN_Counts_3D/MG50_lhs/Transformed_To_Section_Image/'

In [ ]:
#sg_3d = AmiraSpatialGraph(glob.glob(section_graphs_path + file_pattern.format(2))[0],read_header_only=True)
#landmarks3d = Landmarks()
landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 50

with open(tx_file,'r') as f:
    lines = f.readlines()
        
for s in range(120):
    #if len(glob.glob(section_graphs_path + file_pattern.format(s)))>0:
    if 1:
        #file = glob.glob(section_graphs_path + file_pattern.format(s))[0]
        #print(file)
        #sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])

        # read tx mat from the file
        #tx_mat_np = get_tx_mat_from_hx_file(file,lines)
        #print('S{:02d}_00.tif'.format(s))
        tx_mat_np = get_tx_mat_from_hx_file_using_filename('S{:02d}_00.tif'.format(s),lines)
        print(tx_mat_np)
        #print(len(sg.barrels.all_rows_graphdata.edge_pt_coords))
        #sg.set_z_coord(0)
        #sg.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
        #sg.set_z_coord(z_coord)
        #sg.graph_data = sg.combine_subgraphs([sg.pia,sg.wm,\
        #                                              sg.bvs,sg.barrels.all_rows_graphdata,\
        #                                              sg.neuron.all_neurites_subgraphdata])
        z_coord+=z_cood_offset

        #sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
        #print(glob.glob(neun_landmarks_path+'S{}'.format(s)+'/landmarks.landmarkAscii'))
        if len(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii'))>0:
            print(glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0])
            landmark_filename =  glob.glob(neun_landmarks_path+'S{}_'.format(s)+'*Ascii')[0]
            l = Landmarks( landmark_filename )
            #l.set_z_coord(0)
            l.apply_transformation((tx_mat_np),z_coord,trans_2d_only=True)
            l.write_landmarks(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            #print(neun_landmarks_transformed_sections_path+os.path.basename(landmark_filename))
            #l.set_z_coord(z_coord)
            #print(len(l.pts))
            landmarks3d_neun.append_landmarks(l.pts)
        
#         if z_coord == 1000:
#             break
if animal_name == 'MG48_rhs' or animal_name == 'MG49_rhs' or animal_name == 'MG50_rhs':
    axis_direction= [-1,1,1]
    landmarks3d_neun.set_axis_directions(axis=axis_direction)
#landmarks3d_neun.write_landmarks(neun_landmarks_path+'neun_landmarks.LandmarkAscii')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))

# merge the neuron morph
# sg = AmiraSpatialGraph(glob.glob(full_path+'RA*.am')[0],axis_directions=[1,1,1])
# #tx_mat_np = get_tx_mat_from_hx_file(cell_name,lines)
# #print(tx_mat_np)
# #sg.set_z_coord(0)
# #sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
# sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])

# write it
#sg_3d.write_spatial_graph(op_path+animal_name+'_'+cell_name+'.am')
#sg_3d.write_spatial_graph(neun_landmarks_path+'/{}.am'.format(animal_name))  