In [1]:
%run AmiraSpatialGraph.ipynb
import os


In [2]:
HOME=''
for part in (os.getcwd()).split('/')[:-1]:
    HOME = HOME + part + '/'
    
HOME = HOME + 'vM1_Ref_Frame/'

In [3]:

animal_name = 'MG50_lhs'

path = HOME + '0_SpatialGraphs/Section_Graphs/{}/contours/'.format(animal_name)

tx_file = path + 'aligntobarrel.hx'
file_pattern = '*S*_ct.am'

rabies_landmarks_path = HOME + '0_SpatialGraphs/Section_Graphs/{}/rabies/'.format(animal_name)
neun_landmarks_path = '/nas1/Data_Mythreya/MotorCortexProject/V0/0_Inputs/Landmarks/Manual/Rabies/NeuN/{}/'.format(animal_name)

op_path_sg = HOME + '0_SpatialGraphs/3D_Graphs/'
op_path_landmarks = HOME + '0_SpatialGraphs/Landmarks/'

In [44]:
sg_3d = AmiraSpatialGraph(glob.glob(path + file_pattern)[0],read_header_only=True)
landmarks3d = Landmarks()
landmarks3d_neun = Landmarks()

z_coord = 0
z_cood_offset = 100
max_z = 2400#4900
for file in sorted(glob.glob(path + file_pattern)):
    sg = AmiraSpatialGraph(file,axis_directions=[1,1,1])
    print(file)
    
    # read tx mat from the file
    with open(tx_file,'r') as f:
        lines = f.readlines()
        
    str_to_compare = '"'+os.path.basename(file)+'"'+ ' setTransform '
    tx_mat = []
    tx_mat_np = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]).reshape(4,4)
    for line in lines:
        if line.startswith(str_to_compare):
            #tx_mat = (line[len(str_to_compare):-1].split(' '))
            for num in (line[len(str_to_compare):-1].split(' ')):
                tx_mat.append(float(num))
            tx_mat_np = np.array(tx_mat).reshape(4,4)
            break
    
    
    sg.set_z_coord(0)
    
    sg.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
    z_coord+=z_cood_offset
    
    sg_3d.graph_data = sg_3d.combine_subgraphs([sg_3d.graph_data,sg.graph_data])
    
    if len(glob.glob(rabies_landmarks_path+os.path.basename(file)[0:-6]+'*andmarkAscii'))>0:
        rabies_file = glob.glob(rabies_landmarks_path+os.path.basename(file)[0:-6]+'*andmarkAscii')[0]
        print(rabies_file)
        rabies_landmarks = Landmarks(rabies_file)
        rabies_landmarks.set_z_coord(0)
        if len(rabies_landmarks.pts)>0:
            print(tx_mat_np) 
            rabies_landmarks.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
            landmarks3d.append_landmarks(rabies_landmarks.pts)
            
    sec_num = int(os.path.basename(file)[1:-6])
    neun_file = neun_landmarks_path+'S_{}/landmarks.landmarkAscii'.format(str(sec_num))
    print(neun_file)
    #neun_file = '/nas1/Data_Mythreya/MotorCortexProject/V0/0_Inputs/Landmarks/Manual/Rabies/NeuN/MG49_lhs/S_2/landmarks.landmarkAscii'
    #print((neun_file))
    if os.path.exists(neun_file):
        neun_landmarks = Landmarks(neun_file)
        #print(len(neun_landmarks))
        neun_landmarks.set_z_coord(0)
        if len(neun_landmarks.pts)>0:
            print(tx_mat_np) 
            neun_landmarks.apply_transformation(np.transpose(tx_mat_np),z_coord,trans_2d_only=True)
            landmarks3d_neun.append_landmarks(neun_landmarks.pts)
    
    
    #if z_coord == max_z:
    #    break
        
    
sg_3d.write_spatial_graph(op_path_sg+'{}.am'.format(animal_name))
landmarks3d.write_landmarks(op_path_landmarks+'{}_rabies_landmarks.LandmarkAscii'.format(animal_name))
landmarks3d_neun.write_landmarks(op_path_landmarks+'{}_neun_landmarks.LandmarkAscii'.format(animal_name))
    #print((sg.pia.edge_pt_coords))
    

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

[[ 9.74641e-01  2.23775e-01  0.00000e+00  0.00000e+00]
 [-2.23775e-01  9.74641e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.08601e+03  1.50259e+01  3.50000e+02  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.32681e-01  3.60702e-01  0.00000e+00  0.00000e+00]
 [-3.60702e-01  9.32681e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.34149e+03 -4.73512e+02  5.50000e+02  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
B1 Barrel height 0.0
['B2', 19, [1.0, 0.2

[[ 9.95665e-01  9.30020e-02  0.00000e+00  0.00000e+00]
 [-9.30020e-02  9.95665e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 9.24466e+02  5.16437e+02  7.00000e+02  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
A1 Barrel height 0.0
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
B1 Barrel height 0.0

[[ 9.94782e-01  8.64492e-02  0.00000e+00  0.00000e+00]
 [-8.66692e-02  9.96235e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 8.16782e+02 -6.54095e+02  9.50000e+02  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.95291e-01  9.69323e-02  0.00000e+00  0.00000e+00]
 [-9.69323e-02  9.95291e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 8.76196e+02 -4.84345e+02  1.10000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.52283e-01  3.05216e-01  0.00000e+00  0.00000e+00]
 [-3.05216e-01  9.52283e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.92133e+03 -1.72545e+03  1.25000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.57163e-01  2.89551e-01  0.00000e+00  0.00000e+00]
 [-2.89551e-01  9.57163e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.29927e+03 -2.56155e+03  1.40000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.60837e-01  2.77116e-01  0.00000e+00  0.00000e+00]
 [-2.77116e-01  9.60837e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.31706e+03 -2.31695e+03  1.55000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.66330e-01  2.57307e-01  0.00000e+00  0.00000e+00]
 [-2.57307e-01  9.66330e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.18564e+03 -2.84225e+03  1.70000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.29311e-01  3.69297e-01  0.00000e+00  0.00000e+00]
 [-3.69297e-01  9.29311e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.69948e+03 -3.03688e+03  1.85000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.97987e-01  6.34124e-02  0.00000e+00  0.00000e+00]
 [-6.34124e-02  9.97987e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.00007e+03 -2.04264e+03  2.00000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.82214e-01  1.87759e-01  0.00000e+00  0.00000e+00]
 [-1.87759e-01  9.82214e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 2.15291e+02 -3.18818e+03  2.15000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.98166e-01  6.05348e-02  0.00000e+00  0.00000e+00]
 [-6.05348e-02  9.98166e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.14721e+03 -2.68997e+03  2.30000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.96066e-01 -8.86137e-02  0.00000e+00  0.00000e+00]
 [ 8.86137e-02  9.96066e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.47388e+03 -1.09804e+03  2.45000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.98958e-01  4.56457e-02  0.00000e+00  0.00000e+00]
 [-4.56457e-02  9.98958e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-9.60807e+02 -2.58020e+03  2.60000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.99997e-01 -2.49382e-03  0.00000e+00  0.00000e+00]
 [ 2.49382e-03  9.99997e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.31490e+03 -2.37582e+03  2.75000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.96654e-01  8.17373e-02  0.00000e+00  0.00000e+00]
 [-8.17373e-02  9.96654e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-5.71199e+02 -2.42979e+03  2.90000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.92502e-01  1.22228e-01  0.00000e+00  0.00000e+00]
 [-1.22228e-01  9.92502e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-6.31845e+02 -3.06996e+03  3.05000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.96863e-01 -7.91508e-02  0.00000e+00  0.00000e+00]
 [ 7.91508e-02  9.96863e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-3.28304e+03 -1.72898e+03  3.20000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.79735e+03 -2.36016e+03  3.35000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.90801e-01  1.35329e-01  0.00000e+00  0.00000e+00]
 [-1.35329e-01  9.90801e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.52081e+02 -3.01690e+03  3.50000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.85619e-01  1.68982e-01  0.00000e+00  0.00000e+00]
 [-1.68982e-01  9.85619e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-3.91357e+01 -3.19043e+03  3.65000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.98859e-01  4.77619e-02  0.00000e+00  0.00000e+00]
 [-4.77619e-02  9.98859e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.22818e+03 -2.72397e+03  3.80000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.95614e-01  9.35615e-02  0.00000e+00  0.00000e+00]
 [-9.35615e-02  9.95614e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-8.11468e+02 -2.76980e+03  3.95000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.99686e-01  2.50462e-02  0.00000e+00  0.00000e+00]
 [-2.50462e-02  9.99686e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.51528e+03 -2.36659e+03  4.10000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.95900e-01  9.04577e-02  0.00000e+00  0.00000e+00]
 [-9.04577e-02  9.95900e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-8.85649e+02 -3.39614e+03  4.25000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.98974e-01 -4.52829e-02  0.00000e+00  0.00000e+00]
 [ 4.52829e-02  9.98974e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-2.36387e+03 -2.36385e+03  4.40000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

[[ 9.84148e-01  1.77348e-01  0.00000e+00  0.00000e+00]
 [-1.77348e-01  9.84148e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [ 1.71211e+02 -3.11558e+03  4.70000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.94362e-01 -1.06037e-01  0.00000e+00  0.00000e+00]
 [ 1.06037e-01  9.94362e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-3.15453e+03 -1.46757e+03  4.85000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

[[ 9.97128e-01  7.57312e-02  0.00000e+00  0.00000e+00]
 [-7.57312e-02  9.97128e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.11747e+03 -2.68753e+03  5.00000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

[[ 9.99996e-01  2.84311e-03  0.00000e+00  0.00000e+00]
 [-2.84311e-03  9.99996e-01  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.46737e+03 -1.91885e+03  5.45000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
None
None
None
['C1', 23, [1.0, 0.3, 0.3]]
C1 23 [1.0, 0.3, 0.3]
['C2', 24, [1.0, 0.3, 0.3]]
C2 24 [

[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
 [-1.07115e+03 -1.25270e+03  5.90000e+03  1.00000e+00]]
None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0,

In [42]:
#op_path = '/nas1/Data_Mythreya/MotorCortexProject/V2/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/'
axis_direction = [-1,1,1]
sg_3d_mirrored = AmiraSpatialGraph(op_path_sg+'{}.am'.format(animal_name),axis_directions=axis_direction)
sg_3d_mirrored.write_spatial_graph(op_path_sg+'{}_mirrored.am'.format(animal_name))

axis_direction = [1,-1,-1]
landmarks3d.set_axis_directions(axis=axis_direction)
landmarks3d.write_landmarks(op_path_landmarks+'{}_rabies_landmarks_mirrored.LandmarkAscii'.format(animal_name))
landmarks3d_neun.set_axis_directions(axis=axis_direction)
landmarks3d_neun.write_landmarks(op_path_landmarks+'{}_neun_landmarks_mirrored.LandmarkAscii'.format(animal_name))

None
['Pia', 9, [0.0, 1.0, 0.5]]
Pia 9 [0.0, 1.0, 0.5]
None
None
['WhiteMatter', 48, [0.5, 1.0, 0.75]]
WhiteMatter 48 [0.5, 1.0, 0.75]
None
None
['Vessel', 10, [1.0, 0.5, 0.0]]
Vessel 10 [1.0, 0.5, 0.0]
None
['Axon', 6, [0.0, 0.0, 1.0]]
Axon 6 [0.0, 0.0, 1.0]
None
['Soma', 7, [1.0, 0.0, 0.0]]
Soma 7 [1.0, 0.0, 0.0]
None
['ApicalDendrite', 4, [1.0, 0.5, 0.5]]
ApicalDendrite 4 [1.0, 0.5, 0.5]
None
['BasalDendrite', 5, [0.8, 0.4, 0.4]]
BasalDendrite 5 [0.8, 0.4, 0.4]
['A1', 13, [1.0, 0.2, 0.2]]
A1 13 [1.0, 0.2, 0.2]
['A2', 14, [1.0, 0.2, 0.2]]
A2 14 [1.0, 0.2, 0.2]
['A3', 15, [1.0, 0.2, 0.2]]
A3 15 [1.0, 0.2, 0.2]
A3 Barrel height 50.0
['A4', 16, [1.0, 0.2, 0.2]]
A4 16 [1.0, 0.2, 0.2]
None
None
None
['B1', 18, [1.0, 0.25, 0.25]]
B1 18 [1.0, 0.25, 0.25]
B1 Barrel height 0.0
['B2', 19, [1.0, 0.25, 0.25]]
B2 19 [1.0, 0.25, 0.25]
B2 Barrel height 0.0
['B3', 20, [1.0, 0.25, 0.25]]
B3 20 [1.0, 0.25, 0.25]
B3 Barrel height 50.0
['B4', 21, [1.0, 0.25, 0.25]]
B4 21 [1.0, 0.25, 0.25]
B4 Barrel heig

# Coronal directions

In [ ]:
#Slit the landmarks into right and left hemispheres
exp_name = 'MG48'
input_rabies_landmarks = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/' + exp_name + '_combined.landmarkAscii'

hem_name = 'MG48_rhs'
input_sg_file = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/' + hem_name + '.am'
sg = AmiraSpatialGraph(input_sg_file)
bounds = Surface(pts = sg.pia.edge_pt_coords).surface.GetBounds()

output_rabies_landmarks = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/' + hem_name + '.landmarkAscii'
l = Landmarks(filename=input_rabies_landmarks)
cropped_pts = l.get_landmarks_in_bounding_box(bounds)
Landmarks(pts= cropped_pts).write_landmarks(output_rabies_landmarks)

In [ ]:
# transform the spatial graphs to have them in the right orientation
exp_name = 'MG48_rhs'
input_sg = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/' + exp_name + '.am'
input_rabies_landmarks = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/' + exp_name + '.landmarksAscii'
op_path = '/nas1/Data_Mythreya/MotorCortexProject/V5/0_Inputs/SpatialGraphs/Manually_Aligned/Rabies/MG48_cortex/transformed/'

tr_mat = [-1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]
#tr_mat_right = [-1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1]

sg =AmiraSpatialGraph(input_sg)
sg.apply_transformation(transformation_matrix=tr_mat)
sg.write_spatial_graph(op_path+exp_name+'.am')

rabies_landmarks = Landmarks(filename=input_rabies_landmarks)
rabies_landmarks.apply_transformation(transformation_matrix=tr_mat)
rabies_landmarks.write_landmarks(op_path+exp_name+'_rabies_landmarks.LandmarkAscii'.format(animal_name))


In [ ]:
# mirror rhs
exp_name = 'MG48_rhs'
axis_direction = [-1,1,1]
sg_3d_mirrored = AmiraSpatialGraph(op_path+'{}.am'.format(exp_name),axis_directions=axis_direction)
sg_3d_mirrored.write_spatial_graph(op_path+'{}_mirrored.am'.format(exp_name))



In [ ]:

rabies_landmarks = Landmarks(filename=op_path+'{}_rabies_landmarks.LandmarkAscii'.format(exp_name))
rabies_landmarks.set_axis_directions(axis=axis_direction)
#for i in range(len(rabies_landmarks.pts)):
#    rabies_landmarks.pts[i,:] = [rabies_landmarks.pts[i][0]*axis_direction[0],rabies_landmarks.pts[i][1]*axis_direction[1],rabies_landmarks.pts[i][2]*axis_direction[2],0]
rabies_landmarks.write_landmarks(op_path+'{}_rabies_landmarks_mirrored.LandmarkAscii'.format(exp_name))
